# Generated by Django 3.2.5 on 2021-09-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-count_comment']},
        ),
        migrations.AddField(
            model_name='auction',
            name='payment_methods',
            field=models.CharField(choices=[('Trực tiếp', 'Nhận hàng rồi thanh toán'), ('MoMo', 'Thanh toán online bằng MoMo')], default='Trực tiếp', max_length=15),
        ),
    ]
