# Generated by Django 3.2.5 on 2021-09-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_auto_20210917_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='payment_methods',
            new_name='payment_method',
        ),
    ]
