# Generated by Django 3.2.5 on 2021-08-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_auto_20210805_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(blank=True, related_name='hashtag_posts', to='social_network.HashTagPost'),
        ),
    ]
