# Generated by Django 3.2.5 on 2021-09-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='payment_method',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aution_pay_method', to='social_network.paymentmethod'),
        ),
    ]
