# Generated by Django 3.2.5 on 2021-09-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_auction_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioncomment',
            name='status_transaction',
            field=models.CharField(choices=[('Giao dịch thành công', 'Giao dịch thành công'), ('Giao dịch đã bị hủy', 'Giao dịch đã bị hủy'), ('Hai bên đag giao dịch', 'Hai bên đag giao dịch'), ('Chưa giao dịch', 'Chưa giao dịch')], default='Chưa giao dịch', max_length=25),
        ),
        migrations.AlterField(
            model_name='auctionimage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='static/auction_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='static/post_images/%Y/%m'),
        ),
    ]
