# Generated by Django 3.2.5 on 2021-09-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_auto_20210903_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioncomment',
            name='status_transaction',
            field=models.CharField(choices=[('succ', 'Giao dịch thành công'), ('fail', 'Giao dịch đã bị hủy'), ('in process', 'Hai bên đag giao dịch'), ('none', 'Chưa giao dịch')], default='none', max_length=25),
        ),
    ]
