# Generated by Django 3.2.5 on 2021-10-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0007_user_push_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
