# Generated by Django 3.2.5 on 2021-09-04 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0007_alter_auctioncomment_status_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_bought', to=settings.AUTH_USER_MODEL),
        ),
    ]
