# Generated by Django 3.2.5 on 2021-09-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0008_auction_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='date_success',
            field=models.DateTimeField(null=True),
        ),
    ]
