# Generated by Django 3.2.5 on 2021-09-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0010_auto_20210905_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionreport',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
