# Generated by Django 3.2.5 on 2021-09-05 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0011_auto_20210905_0231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepostType',
            new_name='ReportType',
        ),
    ]
