# Generated by Django 3.2.5 on 2021-11-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    operations = [
        migrations.AddField(
            model_name='auction',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
